const profilers = {};
let enabled = true;


/**
 * Convenience function, just returns process.hrtime().
 */
export function start() {
	return process.hrtime();
}

/**
 * Measure from the given time, with the desired key. Returns the time in µs. Params:
 *	- before: time generated by process.hrtime() from which to start measuring.
 *	- key: optional identifier for the profiling.
 *	- showEvery: optional parameter to show results every given iterations.
 */
export function measureFrom(before, key, showEvery) {
	if (!enabled) {
		return;
	}
	const elapsed = process.hrtime(before);
	const diffUs = elapsed[0] * 1e6 + elapsed[1] / 1000;
	if (key) {
		getProfiler(key, showEvery).measure(diffUs);
	}
	return diffUs;
}

export function getProfiler(key, showEvery)
{
	if (!profilers[key] || typeof profilers[key] == 'function')
	{
		profilers[key] = new Profiler(key, showEvery);
	}
	return profilers[key];
}

/**
 * Show profiling data for a key.
 */
export function show(key, showEvery) {
	if (!enabled) {
		return;
	}
	getProfiler(key, showEvery).show();
}

/**
 * Get an object with stats.
 */
export function getStats(key, showEvery) {
	return getProfiler(key, showEvery).getStats(key);
}

/**
 * Disable the whole module.
 */
export function disable() {
	enabled = false;
}

/**
 * Measure some times, show every few requests.
 */
export function Profiler(name, showEvery)
{
	this.name = name;
	this.showEvery = showEvery;
	this.requests = 0;
	this.timeUs = 0;
}

/**
 * Take a measurement, show results every few requests.
 */
Profiler.prototype.measure = function(elapsedUs)
{
	this.requests += 1;
	this.timeUs += elapsedUs;
	if (this.showEvery && this.requests % this.showEvery === 0)
	{
		this.show();
	}
};

Profiler.prototype.show = function()
{
	const stats = this.getStats();
	console.info('Profiling %s: %s requests, mean time: %s µs, rps: %s', this.name, this.requests, stats.meanTimeUs, stats.rps);
	this.requests = 0;
	this.timeUs = 0;
};

Profiler.prototype.getStats = function()
{
	return {
		key: this.name,
		requests: this.requests,
		timeUs: this.timeUs,
		meanTimeUs: (this.timeUs / this.requests).toFixed(3),
		rps: Math.round(this.requests / (this.timeUs / 1e6)),
	};
};

Profiler.prototype.toString = function()
{
	return 'profiler for ' + this.name;
};

